#!/usr/bin/env python

import sys
import os
assert len (sys.argv) == 3
f = open (sys.argv[1])

def read_lsb (f, n = 4):
	ret = 0
	for i in range (n):
		ret += ord (f.read (1)) << (i << 3)
	return ret

n = read_lsb (f) - 1
print '%d files' % n

index = []
for i in range (n):
	offset = read_lsb (f)
	name = f.read (13).rstrip ('\0').lower ()
	index += ([name, offset],)
	print 'file %s @%d' % (name, offset)
end = read_lsb (f)
index += ([None, end],)
print 'end @%d' % end

for i in range (n):
	o = open (os.path.join (sys.argv[2], index[i][0]), 'wb')
	f.seek (index[i][1])
	d = f.read (index[i + 1][1] - index[i][1])
	o.write (d)
