void main ()
{
	wait (1);
	script_attach (1000);
	int eggeric = sp ("eggeric");
	int wife = sp ("wife");
	int chest = sp ("chest");
	freeze (1);
	move_stop (1, 8, 300, 1);
	move_stop (1, 6, 550, 1);
	move_stop (1, 8, 264, 1);
	sp_seq (chest, "chest1");
	wait (1000);
	say_stop ("(Ah, there's that saddle!)", 1);
	say_stop ("`%Bells ringing", 1);
	sp_active (eggeric, 0);
	eggeric = create_sprite (487, 167, "none", "merchant 3", 1);
	sp_speed (eggeric, 2);
	sp_timing (eggeric, 33);
	move_stop (eggeric, 3, 500, 1);
	say_stop ("`0Halt! Who goes there?", eggeric);
	sp_active (wife, 0);
	wife = create_sprite (549, 130, "none", "bluemaiden 1", 1);
	sp_base_walk (wife, "bluemaiden");
	sp_speed (wife, 2);
	sp_timing (wife, 33);
	sp_nohit (wife, 0);
	sp_hitpoints (wife, 100);
	say_stop ("`#What is it? Can't you ever sleep!", wife);
	say_stop ("`0Someone is here, I heard it!", eggeric);
	say_stop ("`#You're just hearing voices.", wife);
	say_stop ("`#What are you so afraid of?", wife);
	say_stop ("`0Oh, Machteld, you're probably right.", eggeric);
	say_stop ("`0I'm much too nervous.", eggeric);
	move_stop (wife, 3, 597, 1);
	move_stop (wife, 1, 555, 1);
	sp_dir (wife, 7);
	say_stop ("`#What is bothering you, then?", wife);
	say_stop ("`0I'm just worried that somebody finds out", eggeric);
	say_stop ("`0that I'll kill king Daniel tomorrow.", eggeric);
	say_stop ("`#You'll kill my brother?", wife);
	say_stop ("`#You can't do that!", wife);
	say_stop ("`0Don't tell me what I can or can't do!", eggeric);
	say_stop ("`0I hate that man!", eggeric);
	say_stop ("`#I will not let you!", wife);
	say_stop ("`0You're my wife and you will not oppose me!", eggeric);
	hurt (wife, 20);
	wait (500);
	say_stop ("`#Ouch! Now I'm bleeding!", wife);
	say_stop ("(and I have your blood on my hands!)", 1);
	say_stop ("`0And remember that if you oppose me again,", eggeric);
	say_stop ("`0it'll be much worse than a bleeding nose!", eggeric);
	say_stop ("(I must get out of here and do something)", 1);
	fade_down_stop ();
	player_map = 35;
	sp_x (1, 400);
	sp_y (1, 0);
	sp_dir (1, 6);
	load_screen ();
	draw_screen ();
	int adelbrecht = sp ("adelbrecht2");
	freeze (1);
	freeze (adelbrecht);
	sp_brain (adelbrecht, "none");
	fade_up ();
	move_stop (1, 2, 150, 1);
	sp_dir (1, 6);
	say_stop ("`9Are we done?", adelbrecht);
	say_stop ("Dude! Terrible news!", 1);
	say_stop ("Eggeric plans to kill king Daniel!", 1);
	say_stop ("`9What? But... Oh! Now I understand...", adelbrecht);
	say_stop ("You understand what?", 1);
	say_stop ("`9Never mind. Er... You should inform er... the king of this.", adelbrecht);
	say_stop ("I can't, I was banished by him, remember?", 1);
	say_stop ("`9Oh, right. So what do we do?", adelbrecht);
	say_stop ("You must tell him.", 1);
	say_stop ("`9But... Er, sure, I can do that.", adelbrecht);
	say_stop ("In case you need me, I'll be in the place where you first met me.", 1);
	say_stop ("`9Right, I'll remember that.", adelbrecht);
	fade_down_stop ();
	say_stop_xy ("So Dink went back to his forest.", 10, 200);
	say_stop_xy ("But soon...", 10, 200);
	player_map = 337;
	sp_x (1, 200);
	sp_y (1, 300);
	sp_dir (1, 6);
	load_screen ();
	draw_screen ();
	adelbrecht = sp ("adelbrecht1");
	sp_y (adelbrecht, 500);
	sp_speed (adelbrecht, 2);
	sp_timing (adelbrecht, 33);
	freeze (adelbrecht);
	freeze (1);
	fade_up ();
	sp_dir (1, 6);
	move_stop (adelbrecht, 8, 320, 1);
	sp_dir (adelbrecht, 7);
	say_stop ("`9Dink! Thank God you're here!", adelbrecht);
	say_stop ("`9I, er, I mean the king needs you!", adelbrecht);
	say_stop ("What for?", 1);
	say_stop ("`9He arrested Eggeric.", adelbrecht);
	say_stop ("`9It seems obvious that he was planning a murder.", adelbrecht);
	say_stop ("`9But there's no proof.", adelbrecht);
	say_stop ("`9He can't just punish him,", adelbrecht);
	say_stop ("`9the people would not allow that.", adelbrecht);
	say_stop ("`9You are a witness!", adelbrecht);
	say_stop ("Not only that,", 1);
	say_stop ("I even have Machteld's blood on my hands to prove it!", 1);
	say_stop ("`9That's even better! Let's go!", adelbrecht);
	fade_down_stop ();
	bedink.main ();
	player_map = 1;
	sp_x (1, 320);
	sp_y (1, 500);
	load_screen ();
	draw_screen ();
	freeze (1);
	dink_can_walk_off_screen (1);
	int daniel = sp ("daniel-intro");
	fade_up ();
	move_stop (1, 8, 300, 1);
	say_stop ("`3SMALLWOOD HAS RETURNED!", daniel);
	say_stop ("Dude, stop shouting.", 1);
	say_stop ("`3Sorry, it's an urge I can't control.", daniel);
	say_stop ("Whatever. You called for me?", 1);
	say_stop ("`3Indeed I did.", daniel);
	say_stop ("You better unbanish me first!", 1);
	say_stop ("`3Sure, if the banishment bothers you...", daniel);
	say_stop ("`3Consider yourself unbanished.", daniel);
	say_stop ("Cool. Now what can I do for you?", 1);
	say_stop ("`3This er... Adelbrecht guy said you had proof against Eggeric.", daniel);
	say_stop ("Indeed I do. This is Machteld's blood.", 1);
	say_stop ("He hit her when she said she didn't want him to kill you.", 1);
	say_stop ("`3Did he now?", daniel);
	say_stop ("`3Well, that's enough proof for me.", daniel);
	say_stop ("`3But I'm afraid it's not enough for the people.", daniel);
	say_stop ("`3They want God to decide.", daniel);
	say_stop ("Of course I know what that means.", 1);
	say_stop ("But I have a feeling people are watching.", 1);
	say_stop ("And they may not know.", 1);
	say_stop ("So just tell me anyway.", 1);
	say_stop ("`3They are?", daniel);
	say_stop ("`3Ah well, nothing secret about it anyway.", daniel);
	say_stop ("`3It means you will have to fight him.", daniel);
	say_stop ("`3God will make sure that the one who speaks the truth will win.", daniel);
	say_stop ("`3I'm confident that it will be you.", daniel);
	say_stop ("Of course it will be me. I'm Dink Smallwood!", 1);
	say_stop ("`3Indeed you are.", daniel);
	say_stop ("`3Go fight him and then return to me.", daniel);
	say_stop ("Sure thing, dude. I'll be right back.", 1);
	say_stop ("`3SMALLWOOD WILL RETURN!", daniel);
	say ("Maybe not, if you keep shouting that!", 1);
	move_stop (1, 2, 500, 1);
	fade_down ();
	player_map = 98;
	sp_x (1, 170);
	sp_y (1, 230);
	sp_dir (1, 6);
	load_screen ();
	draw_screen ();
	dink_can_walk_off_screen (0);
	save_game (-1);
	kill_this_task ();
}
