#!/usr/bin/python

import dink
import Image
import os

name = 'item-w'

d = dink.Dink (None)

def do_extract (seq, dir, bb = None):
	if bb is None:
		bb = seq.boundingbox
	os.mkdir (dir)
	for f, frame in enumerate (seq.frames):
		if frame is None:
			continue
		hw = max (-bb[0], bb[2])
		hh = max (-bb[1], bb[3])
		im = Image.new ('RGB', (2 * hw, 2 * hh), (255, 255, 255))
		fim = Image.open (dink.filepart (*frame.cache))
		fbb = frame.boundingbox
		im.paste (fim, (fbb[0] - bb[0], fbb[1] - bb[1], fbb[2] - bb[0], fbb[3] - bb[1]))
		im.save (os.path.join (dir, '%d.png' % f))

if False:
	c = d.seq.collection[name]
	bb = [max ([c[dir].boundingbox[t] * (-1 if t < 2 else 1) for dir in c if dir in range (1, 10)]) * (-1 if t < 2 else 1) for t in range (4)]
	for dir in c:
		if dir not in range (1, 10):
			continue
		do_extract (c[dir], '%s-%d' % (name, dir), bb)
else:
	do_extract (d.seq.seq[name], name)
