#!/usr/bin/env python
# vim: set foldmethod=marker :

# seqconvert - turn existing dmod graphics into pydink pngs. {{{
# Copyright 2011-2013 Bas Wijnen
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# }}}

# {{{ Imports.
import sys
import os
import Image
import numpy
# }}}

assert len (sys.argv) == 3
assert not os.path.exists (sys.argv[2])
os.makedirs (sys.argv[2])

black = False
# Convert frames to png and change paths.
for f in os.listdir (sys.argv[1]):
	im = Image.open (os.path.join (sys.argv[1], f)).convert ('RGBA')
	ar = numpy.array (im)
	sentinel = 255 if black else 4 * 255	# alpha is always 255 at this point.
	alpha = Image.fromarray (numpy.array (numpy.sum (ar, 2) != sentinel, dtype = numpy.uint8) * 255)
	im.putalpha (alpha)
	base = os.path.splitext (os.path.basename (f))[0]
	filename = os.path.join (sys.argv[2], base + os.extsep + 'png')
	im.save (filename)
